"""Regenerate brain-setup.ps1 from current LIVE brain/ content.

Reads all dashboard/pipeline files and embeds them as PowerShell here-strings
into a fresh setup script. This avoids hand-maintaining 200 KB of templated
heredocs and recovers from any sync corruption.
"""
from __future__ import annotations
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT  = ROOT / "windows" / "install.ps1"


def load(p: Path) -> str:
    text = p.read_text(encoding="utf-8")
    # Strip BOM if present
    if text and text[0] == "﻿":
        text = text[1:]
    return text.replace("\r\n", "\n").rstrip("\n")


# Load all live content
EMBEDS = {
    "backendPy":  load(ROOT / "dashboard" / "app.py"),
    "mcpRunnerPy": load(ROOT / "dashboard" / "mcp_runner.py"),
    "trayPy":     load(ROOT / "dashboard" / "tray.py"),
    "mcpRagPy":   load(ROOT / "dashboard" / "mcp_rag.py"),
    "html":       load(ROOT / "dashboard" / "static" / "index.html"),
    "css":        load(ROOT / "dashboard" / "static" / "style.css"),
    "js":         load(ROOT / "dashboard" / "static" / "app.js"),
    "favicon":    load(ROOT / "dashboard" / "static" / "favicon.svg"),
    "distillPy":  load(ROOT / "pipeline"  / "distill.py"),
    "ragPy":      load(ROOT / "pipeline"  / "rag.py"),
    "dedupePy":   load(ROOT / "pipeline"  / "dedupe.py"),
    "skillsPy":   load(ROOT / "pipeline"  / "skills.py"),
    "codeIndexPy": load(ROOT / "pipeline" / "codeindex.py"),
    "redistillPy": load(ROOT / "pipeline" / "redistill.py"),
    "schedulerPy": load(ROOT / "pipeline" / "scheduler.py"),
    "agentsPy":   load(ROOT / "pipeline" / "agents.py"),
    "makeIconPy": load(ROOT / "pipeline"  / "make_icon.py"),
    "stopPs1":    load(ROOT / "stop.ps1"),
    "startPs1":   load(ROOT / "start.ps1"),
    "brainBat":   load(ROOT / "brain.bat"),
    "launchCmd":  load(ROOT / "launch.cmd"),
    "makeShortcutPs1": load(ROOT / "make-shortcut.ps1"),
}

# Auto-discover skills (brain/skills/*.md) — each becomes its own embed var
# with name "skill_<stem>" so we can write all of them in the setup script.
SKILLS_DIR = ROOT / "skills"
SKILL_FILES: dict[str, str] = {}
if SKILLS_DIR.exists():
    for sp in sorted(SKILLS_DIR.glob("*.md")):
        # Sanitize stem to valid PS variable name: alphanumeric + underscore
        key = "skill_" + "".join(c if c.isalnum() else "_" for c in sp.stem)
        EMBEDS[key] = load(sp)
        SKILL_FILES[sp.name] = key


def heredoc(var: str, content: str) -> str:
    """Build a PowerShell single-quoted here-string assignment.
    Critical: closing '@ must be at column 0 on its own line."""
    # Single-quoted here-string treats '' as escape for '. We don't actually
    # need to escape anything else.
    return f"${var} = @'\n{content}\n'@"


TEMPLATE = r"""<#
.SYNOPSIS
  Brain — portable AI hub for Windows. Generated by regenerate_setup.py.
.PARAMETER Root
  Root install directory. Default: <script-dir>\brain
.PARAMETER Model
  Initial Ollama model to pull. Default: qwen2.5:14b
.PARAMETER SkipModelPull
  Skip pulling the model.
.PARAMETER SkipPython
  Skip embedded Python install.
#>

[CmdletBinding()]
param(
    [string]$Root = $(if ($PSScriptRoot) { Join-Path $PSScriptRoot "brain" } else { Join-Path (Get-Location) "brain" }),
    [string]$Model = "qwen2.5:14b",
    [int]$DashboardPort = 7860,
    [int]$OllamaPort = 11434,
    [switch]$SkipModelPull,
    [switch]$SkipPython
)

$ErrorActionPreference = "Stop"
$ProgressPreference = "SilentlyContinue"

$P = [ordered]@{
    Root      = $Root
    Bin       = Join-Path $Root "bin"
    Python    = Join-Path $Root "bin\python"
    Ollama    = Join-Path $Root "bin\ollama"
    Data      = Join-Path $Root "data"
    Models    = Join-Path $Root "data\ollama-models"
    Vault     = Join-Path $Root "data\vault"
    Distilled = Join-Path $Root "data\distilled"
    VectorDb  = Join-Path $Root "data\vectordb"
    Library   = Join-Path $Root "data\library"
    Backups   = Join-Path $Root "data\backups"
    Pipeline  = Join-Path $Root "pipeline"
    Skills    = Join-Path $Root "skills"
    Dashboard = Join-Path $Root "dashboard"
    Static    = Join-Path $Root "dashboard\static"
    Logs      = Join-Path $Root "logs"
}

function Write-Step($m) { Write-Host ""; Write-Host ">> $m" -ForegroundColor Cyan }
function Write-Ok($m)   { Write-Host "   [ok] $m" -ForegroundColor Green }
function Write-Warn2($m){ Write-Host "   [!!] $m" -ForegroundColor Yellow }
function Write-Err2($m) { Write-Host "   [xx] $m" -ForegroundColor Red }

Write-Host ""
Write-Host "==================================================================" -ForegroundColor Magenta
Write-Host "  BRAIN setup -- portable AI hub" -ForegroundColor Magenta
Write-Host "  Root: $Root" -ForegroundColor DarkGray
Write-Host "==================================================================" -ForegroundColor Magenta

Write-Step "Creating directory tree"
foreach ($k in $P.Keys) {
    if (-not (Test-Path $P[$k])) { New-Item -ItemType Directory -Path $P[$k] -Force | Out-Null }
}
Write-Ok "Tree ready"

Write-Step "Detecting GPU"
$Gpu = @{ Vendor="unknown"; Name="(none)"; VramMB=0; HipSdk=$false; HipPath=$null; Cuda=$false }
$adapters = Get-CimInstance Win32_VideoController -ErrorAction SilentlyContinue
foreach ($a in $adapters) {
    $n = $a.Name
    if ($n -match "NVIDIA|GeForce|RTX|GTX|Quadro|Tesla") {
        $Gpu.Vendor="nvidia"; $Gpu.Name=$n; $Gpu.VramMB=[math]::Round($a.AdapterRAM/1MB); $Gpu.Cuda=$true; break
    } elseif ($n -match "AMD|Radeon|RX ") {
        $Gpu.Vendor="amd"; $Gpu.Name=$n; $Gpu.VramMB=[math]::Round($a.AdapterRAM/1MB)
    } elseif ($n -match "Intel" -and $Gpu.Vendor -eq "unknown") {
        $Gpu.Vendor="intel"; $Gpu.Name=$n; $Gpu.VramMB=[math]::Round($a.AdapterRAM/1MB)
    }
}
if ($Gpu.Vendor -in @("amd","nvidia")) {
    $base = "HKLM:\SYSTEM\CurrentControlSet\Control\Class\{4d36e968-e325-11ce-bfc1-08002be10318}"
    Get-ChildItem $base -ErrorAction SilentlyContinue | ForEach-Object {
        $props = Get-ItemProperty $_.PSPath -ErrorAction SilentlyContinue
        if ($props."HardwareInformation.qwMemorySize") {
            $mb = [math]::Round([int64]$props."HardwareInformation.qwMemorySize"/1MB)
            if ($mb -gt $Gpu.VramMB) { $Gpu.VramMB = $mb }
        }
    }
}
Write-Ok "Vendor: $($Gpu.Vendor) - Name: $($Gpu.Name) - VRAM: $($Gpu.VramMB) MB"
if ($Gpu.Vendor -eq "amd") {
    Write-Ok "Using Vulkan backend (no HIP SDK needed; OLLAMA_VULKAN=1 set by start.ps1)"
}

if (-not $SkipPython) {
    Write-Step "Installing embedded Python 3.12"
    $pyExe = Join-Path $P.Python "python.exe"
    if (Test-Path $pyExe) {
        Write-Ok "Already present: $pyExe"
    } else {
        $pyUrl = "https://www.python.org/ftp/python/3.12.7/python-3.12.7-embed-amd64.zip"
        $pyZip = Join-Path $env:TEMP "python-embed.zip"
        Invoke-WebRequest -Uri $pyUrl -OutFile $pyZip
        Expand-Archive -Path $pyZip -DestinationPath $P.Python -Force
        Remove-Item $pyZip
        $pth = Get-ChildItem $P.Python -Filter "python3*._pth" | Select-Object -First 1
        if ($pth) {
            (Get-Content $pth.FullName) -replace '^#\s*import site', 'import site' | Set-Content $pth.FullName -Encoding ASCII
        }
        $getPip = Join-Path $env:TEMP "get-pip.py"
        Invoke-WebRequest "https://bootstrap.pypa.io/get-pip.py" -OutFile $getPip
        & $pyExe $getPip --no-warn-script-location
        Remove-Item $getPip
        Write-Ok "Python installed"
    }

    Write-Step "Installing Python deps"
    & $pyExe -m pip install --upgrade pip --quiet
    & $pyExe -m pip install --quiet fastapi "uvicorn[standard]" psutil requests pydantic httpx pystray pillow pymupdf sqlite-vec mcp ebooklib python-docx beautifulsoup4 py7zr mobi
    Write-Ok "Deps installed"
}

Write-Step "Installing Ollama"
$ollamaExe = Join-Path $P.Ollama "ollama.exe"
if (Test-Path $ollamaExe) {
    Write-Ok "Already present"
} else {
    $url = "https://github.com/ollama/ollama/releases/latest/download/ollama-windows-amd64.zip"
    $zip = Join-Path $env:TEMP "ollama-windows.zip"
    Invoke-WebRequest -Uri $url -OutFile $zip
    Expand-Archive -Path $zip -DestinationPath $P.Ollama -Force
    Remove-Item $zip
    if (-not (Test-Path $ollamaExe)) {
        $found = Get-ChildItem $P.Ollama -Recurse -Filter "ollama.exe" | Select-Object -First 1
        if ($found) { Move-Item $found.FullName $ollamaExe -Force }
    }
    Write-Ok "Ollama installed"
}

Write-Step "Writing config.json"
$cfg = [ordered]@{
    version="0.4.0"; root=$Root; ollama_port=$OllamaPort; dashboard_port=$DashboardPort
    default_model=$Model; gpu=$Gpu
}
$cfg | ConvertTo-Json -Depth 6 | Set-Content (Join-Path $Root "config.json") -Encoding UTF8
Write-Ok "config.json written"

# === EMBEDDED FILES ===

__EMBEDS__

Set-Content -Path (Join-Path $P.Dashboard "app.py")          -Value $backendPy   -Encoding UTF8
Set-Content -Path (Join-Path $P.Dashboard "mcp_runner.py")   -Value $mcpRunnerPy -Encoding UTF8
Set-Content -Path (Join-Path $P.Dashboard "tray.py")         -Value $trayPy      -Encoding UTF8
Set-Content -Path (Join-Path $P.Dashboard "mcp_rag.py")      -Value $mcpRagPy    -Encoding UTF8
Set-Content -Path (Join-Path $P.Static    "index.html")      -Value $html        -Encoding UTF8
Set-Content -Path (Join-Path $P.Static    "style.css")       -Value $css         -Encoding UTF8
Set-Content -Path (Join-Path $P.Static    "app.js")          -Value $js          -Encoding UTF8
Set-Content -Path (Join-Path $P.Static    "favicon.svg")     -Value $favicon     -Encoding UTF8
Set-Content -Path (Join-Path $P.Pipeline  "distill.py")      -Value $distillPy   -Encoding UTF8
Set-Content -Path (Join-Path $P.Pipeline  "rag.py")          -Value $ragPy       -Encoding UTF8
Set-Content -Path (Join-Path $P.Pipeline  "dedupe.py")       -Value $dedupePy    -Encoding UTF8
Set-Content -Path (Join-Path $P.Pipeline  "skills.py")       -Value $skillsPy    -Encoding UTF8
Set-Content -Path (Join-Path $P.Pipeline  "codeindex.py")    -Value $codeIndexPy -Encoding UTF8
Set-Content -Path (Join-Path $P.Pipeline  "redistill.py")    -Value $redistillPy -Encoding UTF8
Set-Content -Path (Join-Path $P.Pipeline  "scheduler.py")    -Value $schedulerPy -Encoding UTF8
Set-Content -Path (Join-Path $P.Pipeline  "agents.py")       -Value $agentsPy    -Encoding UTF8
Set-Content -Path (Join-Path $P.Pipeline  "mcp-servers.json") -Value "[]`n"     -Encoding UTF8
Set-Content -Path (Join-Path $P.Pipeline  "make_icon.py")    -Value $makeIconPy  -Encoding UTF8
__SKILLS_EMIT__
Set-Content -Path (Join-Path $Root        "stop.ps1")        -Value $stopPs1     -Encoding UTF8
Set-Content -Path (Join-Path $Root        "brain.bat")       -Value $brainBat    -Encoding ASCII
Set-Content -Path (Join-Path $Root        "launch.cmd")      -Value $launchCmd   -Encoding ASCII
Set-Content -Path (Join-Path $Root        "make-shortcut.ps1") -Value $makeShortcutPs1 -Encoding UTF8

# make-shortcut.cmd wrapper
$makeShortcutCmd = "@echo off`r`npowershell.exe -NoProfile -ExecutionPolicy Bypass -File `"%~dp0make-shortcut.ps1`" %*`r`npause`r`n"
Set-Content -Path (Join-Path $Root "make-shortcut.cmd") -Value $makeShortcutCmd -Encoding ASCII

# Generate brain.ico if Python is installed (otherwise skip — user can do it later)
$pyExe = Join-Path $P.Python "python.exe"
$makeIconScript = Join-Path $P.Pipeline "make_icon.py"
if ((Test-Path $pyExe) -and (Test-Path $makeIconScript)) {
    try {
        & $pyExe $makeIconScript | Out-Null
        Write-Ok "brain.ico generated"
    } catch {
        Write-Warn2 "brain.ico generation failed; run later: bin\python\python.exe pipeline\make_icon.py"
    }
}

Write-Ok "All files written"

# start.ps1 — embedded from live file (tray is now the master process)
Set-Content -Path (Join-Path $Root "start.ps1") -Value $startPs1 -Encoding UTF8

$startCmd = "@echo off`r`npowershell.exe -NoProfile -ExecutionPolicy Bypass -File `"%~dp0start.ps1`" %*`r`n"
$stopCmd  = "@echo off`r`npowershell.exe -NoProfile -ExecutionPolicy Bypass -File `"%~dp0stop.ps1`" %*`r`n"
Set-Content -Path (Join-Path $Root "start.cmd") -Value $startCmd -Encoding ASCII
Set-Content -Path (Join-Path $Root "stop.cmd")  -Value $stopCmd  -Encoding ASCII
Write-Ok "Launchers written"

if (-not $SkipModelPull) {
    Write-Step "Pulling initial model: $Model"
    $env:OLLAMA_MODELS = $P.Models
    $env:OLLAMA_HOST   = "127.0.0.1:$OllamaPort"
    $env:OLLAMA_VULKAN = "1"
    $proc = Start-Process -FilePath $ollamaExe -ArgumentList "serve" -WindowStyle Hidden -PassThru
    Start-Sleep -Seconds 3
    try { & $ollamaExe pull $Model; Write-Ok "Model pulled" }
    catch { Write-Warn2 "Pull failed; you can retry with: .\bin\ollama\ollama.exe pull $Model" }
    finally { Stop-Process -Id $proc.Id -Force -ErrorAction SilentlyContinue }
}

Write-Host ""
Write-Host "==================================================================" -ForegroundColor Magenta
Write-Host "  DONE."  -ForegroundColor Magenta
Write-Host "  cd $Root  &&  .\start.cmd  (or double-click brain.bat for menu)"
Write-Host "==================================================================" -ForegroundColor Magenta
"""


def main():
    embeds_block = "\n\n".join(heredoc(name, content) for name, content in EMBEDS.items())
    # Generate per-skill emit lines (Skills directory already created by P loop)
    skill_emits = "\n".join(
        f'Set-Content -Path (Join-Path $P.Skills "{fname}") -Value ${var} -Encoding UTF8'
        for fname, var in SKILL_FILES.items()
    )
    output = TEMPLATE.replace("__EMBEDS__", embeds_block)
    output = output.replace("__SKILLS_EMIT__", skill_emits)
    OUT.write_text(output, encoding="utf-8")
    size_kb = OUT.stat().st_size / 1024
    print(f"[ok] wrote {OUT} ({size_kb:.1f} KB)")

    # Validate via PS parser
    import subprocess
    r = subprocess.run(
        ["powershell.exe", "-NoProfile", "-Command",
         f"$errs=$null; $toks=$null; "
         f"$null=[System.Management.Automation.Language.Parser]::ParseFile("
         f"'{OUT}', [ref]$toks, [ref]$errs); "
         f"Write-Host \"parse_errors=$($errs.Count)\"; "
         f"if($errs.Count -gt 0){{ $errs | Select-Object -First 3 | "
         f"ForEach-Object {{ Write-Host \"L$($_.Extent.StartLineNumber): $($_.Message)\" }} }}"],
        capture_output=True, text=True, timeout=30,
    )
    print(r.stdout.strip())
    if r.stderr.strip(): print("stderr:", r.stderr.strip())


if __name__ == "__main__":
    main()
